apiVersion: v1
kind: Service
metadata:
  name: icwebapp
  namespace: icgroup
  labels:
    app: icwebapp
    environment: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30280
  selector:
    app: icwebapp
    tier: frontend