apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: backend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: odoo-db-pvc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/mayas/pv-01
    server: Ubuntu-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
  labels:
    app: odoo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      containers:
        - name: odoo-db
          image: postgres:13
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
            - name: POSTGRES_DB
              value: postgres
          ports:
            - name: odoo-db
              containerPort: 5432
          volumeMounts:
            - name: odoo-db-persistent-storage
              mountPath: /var/lib/odoo
      volumes:
        - name: odoo-db-persistent-storage
          persistentVolumeClaim:
            claimName: odoo-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - port: 8069
  selector:
    app: odoo
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      containers:
        - name: odoo-shop
          image: odoo:13.0
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          env:
            - name: HOST
              value: odoo-db
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          ports:
            - name: odoo-shop
              containerPort: 8069