apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      containers:
        - name: odoo-db
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
            - name: POSTGRES_DB
              value: postgres
          ports:
            - name: odoo-db
              containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - port: 8069
  selector:
    app: odoo
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      containers:
        - name: odoo-shop
          image: odoo:13.0
          env:
            - name: HOST
              value: odoo-db
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          ports:
            - name: odoo-shop
              containerPort: 8069
