apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      containers:
        - name: odoo-db
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
            - name: POSTGRES_DB
              value: postgres
          ports:
            - name: odoo-db
              containerPort: 5432
          volumenMounts:
            - name: odoo-db-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: odoo-db-pvc
          persistentVolumeClaim:
            claimName: odoo-db-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - port: 8069
  selector:
    app: odoo
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      containers:
        - name: odoo-shop
          image: odoo:13.0
          env:
            - name: HOST
              value: odoo-db
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          ports:
            - name: odoo-shop
              containerPort: 8069
          volumenMounts:
            - name: odoo-pvc
              mountPath: /var/lib/odoo
      volumes:
        - name: odoo-pvc
          persistentVolumeClaim:
            claimName: odoo-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv0001
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
  labels:
    app: odoo
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  labels:
    app: odoo
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
