apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    environment: prod
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: pgadmin
    tier: frontend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-03
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/mayas/pv-03
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  labels:
    app: pgadmin
    environment: prod
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    environment: prod
data:
  PGADMIN_DEFAULT_EMAIL: mayasaeh213@gmail.com
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    environment: prod
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: MDgwMzE5OTg=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
    environment: prod
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Minimally Defined Server",
          "Group": "Server Group 1",
          "Port": 30200,
          "Username": "odoo",
          "Host": "192.168.245.148",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        tier: frontend
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:6.2
          securityContext:
            privileged: true
            runAsUser: 0
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: pgadmin
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - name: pgadmin
              containerPort: 80
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgadmin-persistent-storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
        - name: pgadmin-persistent-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc
...